### ISSUE TITLE
entry summary vs content

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging#42]
Some feeds have content in the summary, some in content. We need to check to use summary if content is empty.

**Comment by FredvonHeymann** [comment]
should be fixed by changing  get_feedparser_entry_content(entry) in main.py like so:
def get_feedparser_entry_content(entry):
    try:
        return " ".join([content.value for content in entry.content])
    except AttributeError:
        try:
            return " ".join([content.value for content in entry.summary])
        except AttributeError:
            return ""

**Comment by FredvonHeymann** [comment]
okay, after more testing, this doesn't solve the problem :(

**Comment by FredvonHeymann** [comment]
solved, see https://github.com/fbreuer/mathblogging/commit/fe5301f84e26fb3a1583d11e80449f118c12fbc8
