### ISSUE TITLE
app engine -- log errors

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging#59]
Error in log: 

"You don't have the C version of NameMapper installed! I'm disabling Cheetah's useStackFrames option as it is painfully slow with the Python version of NameMapper. You should get a copy of Cheetah with the compiled C version of NameMapper." 

What can be done?

**Comment by fbreuer** [comment]
There is nothing that can be done, I am afraid. We cannot install the C
version on the Google server and so Cheetah will keep nagging. We could hack
the Cheetah source of course...

Am 04.05.2011 02:22 schrieb "pkra" <
reply@reply.github.com>:

**Comment by FredvonHeymann** [comment]
can be indeed 'solved' by setting 'useStackFrames' to False by default in Compiler.py (line 54) and commenting the 'if' loop at line 1506
