### ISSUE TITLE
menu blogs vs blog

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging#63]
The menu has "blogs" for the category view, "blog" for our developer blog.

To be changed to "all blogs" and "our blog"

**Comment by fbreuer** [comment]
frage: wollen wir "our blog" nicht einfach weglassen, jetzt wo die weekly
picks direkt auf der webseite sind und dort auch ein link zum wordpress blog
zu finden ist?

Am 28.05.2011 22:28 schrieb "pkra" <
reply@reply.github.com>:
The menu has "blogs" for the category view, "blog" for our developer blog.

To be changed to "all blogs" and "our blog"

## 

Reply to this email directly or view it on GitHub:
https://github.com/fbreuer/mathblogging/issues/63

**Comment by pkra** [comment]
how about "our blog" back to "about"? I'd like to leave it there in any case.

**Comment by fbreuer** [comment]
"about" sounds good.

Am 30.05.2011 03:51 schrieb "pkra" <
reply@reply.github.com>:

**Comment by pkra** [comment]
Blog -> "about us"
