### ISSUE TITLE
communities appear in stats-view

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging#64]
Reddit, mathoverflow

**Comment by fbreuer** [comment]
das hatte sich aus performance grnden so ergeben. momentan wrde es am
meisten sinn mach, die communities im template und nicht in main.py
herauszufiltern, wenn wir sowieso ber die feeds iterieren.

Am 28.05.2011 22:29 schrieb "pkra" <
reply@reply.github.com>:

**Comment by pkra** [comment]
It's working in the current code -- which is a mystery to me...

**Comment by pkra** [comment]
has been corrected.
