### ISSUE TITLE
planettag: speed issues 

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging#75]
It's extremely slow. The loading of the posts makes browsers think that the cloud-js is too slow since it's rendered after.

We could
- drop the "planet" (reproduction of posts) and just give lists of posts
- do that as jquery-overlay-fancy
- Could iframes help to speed up cloud rendering 
- We could give a list + iframes as overlay-fancy

**Comment by fbreuer** [comment]
cloud rendering speed is not affected by the time it takes to load the
entire html source.

Am 07.06.2011 17:44 schrieb "pkra" <
reply@reply.github.com>:

**Comment by pkra** [comment]
Aber

http://peter.krautzberger.info
On Jun 7, 2011 1:11 PM, "fbreuer" <
reply@reply.github.com>
wrote:

**Comment by pkra** [comment]
Then why do browsers ask to kill the script?

**Comment by pkra** [comment]
it's better now.
