### ISSUE TITLE
delete old entries from database

### ISSUE THREAD

**Issue by FredvonHeymann** [mathblogging/mathblogging#89]
Am I wrong or do we just keep all entries that we ever put in the database? There should be something (once a week?) to clean out old entries.

**Comment by pkra** [comment]
Yes, we keep all of them.

We had planned on emptying them out once a month, I think.

**Comment by FredvonHeymann** [comment]
maybe its better to go through the entries more often and purge the ones that are older than a month (or 2 or whatever). Otherwise we have the problem again that it seems to be expensive to delete a lot at once.

**Comment by pkra** [comment]
Sure. That sounds like a good idea.

**Comment by pkra** [comment]
Code is on staging. We'll have to see if it does what it's supposed to. Otherwise, we'll reopen this...
